# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "openehr"
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shinji KOBAYASHI", "Akimichi Tatsukawa"]
  s.date = "2012-05-04"
  s.description = "This project is an implementation of the openEHR specification on Ruby."
  s.email = "skoba@moss.gr.jp"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Guardfile",
    "History.txt",
    "PostInstall.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "doc/openehr_terminology.xml",
    "lib/openehr.rb",
    "lib/openehr/am.rb",
    "lib/openehr/am/archetype.rb",
    "lib/openehr/am/archetype/assertion.rb",
    "lib/openehr/am/archetype/constraint_model.rb",
    "lib/openehr/am/archetype/constraint_model/primitive.rb",
    "lib/openehr/am/archetype/ontology.rb",
    "lib/openehr/am/openehr_profile.rb",
    "lib/openehr/am/openehr_profile/data_types.rb",
    "lib/openehr/am/openehr_profile/data_types/basic.rb",
    "lib/openehr/am/openehr_profile/data_types/quantity.rb",
    "lib/openehr/am/openehr_profile/data_types/text.rb",
    "lib/openehr/assumed_library_types.rb",
    "lib/openehr/parser.rb",
    "lib/openehr/parser/adl.rb",
    "lib/openehr/parser/adl_grammar.tt",
    "lib/openehr/parser/adl_parser.rb",
    "lib/openehr/parser/cadl_grammar.tt",
    "lib/openehr/parser/cadl_node.rb",
    "lib/openehr/parser/dadl.rb",
    "lib/openehr/parser/dadl_grammar.tt",
    "lib/openehr/parser/exception.rb",
    "lib/openehr/parser/shared_token_grammar.tt",
    "lib/openehr/parser/validator.rb",
    "lib/openehr/parser/xml_perser.rb",
    "lib/openehr/rm.rb",
    "lib/openehr/rm/common.rb",
    "lib/openehr/rm/common/archetyped.rb",
    "open_ehr.gemspec",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/skoba/ruby-impl-openehr"
  s.licenses = ["Apache 2.0 license"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Ruby implementation of the openEHR specification"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xml-simple>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<locale>, [">= 0"])
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<treetop>, [">= 0"])
      s.add_runtime_dependency(%q<polyglot>, [">= 0"])
      s.add_runtime_dependency(%q<rdoc>, [">= 0"])
      s.add_runtime_dependency(%q<sqlite3>, [">= 0"])
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<spork>, ["~> 1.0rc"])
      s.add_development_dependency(%q<guard-spork>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<libnotify>, [">= 0"])
    else
      s.add_dependency(%q<xml-simple>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<locale>, [">= 0"])
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<treetop>, [">= 0"])
      s.add_dependency(%q<polyglot>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<spork>, ["~> 1.0rc"])
      s.add_dependency(%q<guard-spork>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<libnotify>, [">= 0"])
    end
  else
    s.add_dependency(%q<xml-simple>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<locale>, [">= 0"])
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<treetop>, [">= 0"])
    s.add_dependency(%q<polyglot>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<spork>, ["~> 1.0rc"])
    s.add_dependency(%q<guard-spork>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<libnotify>, [">= 0"])
  end
end

