# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{open_ehr}
  s.version = "0.6.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shinji KOBAYASHI", "Akimichi Tatsukawa"]
  s.date = %q{2011-05-09}
  s.description = %q{This project is an implementation of the openEHR specification on Ruby.}
  s.email = %q{skoba@moss.gr.jp}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "History.txt",
    "Manifest.txt",
    "PostInstall.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "doc/openehr_terminology.xml",
    "lib/#open_ehr.rb#",
    "lib/open_ehr.rb",
    "lib/open_ehr/am.rb",
    "lib/open_ehr/am/archetype.rb",
    "lib/open_ehr/am/archetype/archetype_description/archetype_description.rb",
    "lib/open_ehr/am/archetype/assertion.rb",
    "lib/open_ehr/am/archetype/constraint_model.rb",
    "lib/open_ehr/am/archetype/constraint_model/primitive.rb",
    "lib/open_ehr/am/archetype/ontology.rb",
    "lib/open_ehr/am/open_ehr_profile/data_types/basic.rb",
    "lib/open_ehr/am/open_ehr_profile/data_types/quantity.rb",
    "lib/open_ehr/am/open_ehr_profile/data_types/text.rb",
    "lib/open_ehr/assumed_library_types.rb",
    "lib/open_ehr/parser.rb",
    "lib/open_ehr/parser/xml_perser.rb",
    "lib/open_ehr/rm.rb",
    "lib/open_ehr/rm/common.rb",
    "lib/open_ehr/rm/common/archetyped.rb",
    "lib/open_ehr/rm/common/change_control.rb",
    "lib/open_ehr/rm/common/directory.rb",
    "lib/open_ehr/rm/common/generic.rb",
    "lib/open_ehr/rm/common/resource.rb",
    "lib/open_ehr/rm/composition.rb",
    "lib/open_ehr/rm/composition/content.rb",
    "lib/open_ehr/rm/composition/content/entry.rb",
    "lib/open_ehr/rm/composition/content/navigation.rb",
    "lib/open_ehr/rm/data_structures.rb",
    "lib/open_ehr/rm/data_structures/history.rb",
    "lib/open_ehr/rm/data_structures/item_structure.rb",
    "lib/open_ehr/rm/data_structures/item_structure/representation.rb",
    "lib/open_ehr/rm/data_types.rb",
    "lib/open_ehr/rm/data_types/basic.rb",
    "lib/open_ehr/rm/data_types/charset.lst",
    "lib/open_ehr/rm/data_types/charset_extract.rb",
    "lib/open_ehr/rm/data_types/encapsulated.rb",
    "lib/open_ehr/rm/data_types/quantity.rb",
    "lib/open_ehr/rm/data_types/quantity/date_time.rb",
    "lib/open_ehr/rm/data_types/text.rb",
    "lib/open_ehr/rm/data_types/time_specification.rb",
    "lib/open_ehr/rm/data_types/uri.rb",
    "lib/open_ehr/rm/demographic.rb",
    "lib/open_ehr/rm/ehr.rb",
    "lib/open_ehr/rm/integration.rb",
    "lib/open_ehr/rm/security.rb",
    "lib/open_ehr/rm/support.rb",
    "lib/open_ehr/rm/support/assumed_types.rb",
    "lib/open_ehr/rm/support/definition.rb",
    "lib/open_ehr/rm/support/identification.rb",
    "lib/open_ehr/rm/support/measurement.rb",
    "lib/open_ehr/rm/support/terminology.rb",
    "lib/open_ehr/serializer.rb",
    "lib/open_ehr/terminology.rb",
    "lib/open_ehr/terminology/open_ehr_terminology.rb",
    "lib/open_ehr/writer.rb",
    "open_ehr.gemspec",
    "spec/lib/open_ehr/am/archetype/archetype_spec.rb",
    "spec/lib/open_ehr/am/archetype/assertion/assertion_spec.rb",
    "spec/lib/open_ehr/am/archetype/assertion/assertion_variable_spec.rb",
    "spec/lib/open_ehr/am/archetype/assertion/expr_binary_operator.rb",
    "spec/lib/open_ehr/am/archetype/assertion/expr_item_spec.rb",
    "spec/lib/open_ehr/am/archetype/assertion/expr_leaf_spec.rb",
    "spec/lib/open_ehr/am/archetype/assertion/expr_operator_spec.rb",
    "spec/lib/open_ehr/am/archetype/assertion/expr_unary_operator_spec.rb",
    "spec/lib/open_ehr/am/archetype/assertion/operator_kind_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/archetype_constraint_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/archetype_internal_ref_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/archetype_slot_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/c_attribute_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/c_complex_object_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/c_defined_object_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/c_domain_type_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/c_multiple_attribute_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/c_object_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/c_primitive_object_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/c_reference_object_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/c_single_attribute_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/cardinality_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/constraint_ref_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/primitive/c_boolean_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/primitive/c_date_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/primitive/c_date_time_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/primitive/c_duration_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/primitive/c_integer_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/primitive/c_primitive_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/primitive/c_real_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/primitive/c_string_spec.rb",
    "spec/lib/open_ehr/am/archetype/constraint_model/primitive/c_time_spec.rb",
    "spec/lib/open_ehr/am/archetype/ontology/archetype_ontology_spec.rb",
    "spec/lib/open_ehr/am/archetype/ontology/archetype_term_spec.rb",
    "spec/lib/open_ehr/am/archetype/validity_kind_spec.rb",
    "spec/lib/open_ehr/assumed_library_types/interval_spec.rb",
    "spec/lib/open_ehr/assumed_library_types/iso8601_date_spec.rb",
    "spec/lib/open_ehr/assumed_library_types/iso8601_date_time_spec.rb",
    "spec/lib/open_ehr/assumed_library_types/iso8601_duration_spec.rb",
    "spec/lib/open_ehr/assumed_library_types/iso8601_time_spec.rb",
    "spec/lib/open_ehr/assumed_library_types/iso8601_timezone_spec.rb",
    "spec/lib/open_ehr/assumed_library_types/time_definitions_spec.rb",
    "spec/lib/open_ehr/rm/common/archetyped/archetyped_spec.rb",
    "spec/lib/open_ehr/rm/common/archetyped/feeder_audit_details_spec.rb",
    "spec/lib/open_ehr/rm/common/archetyped/feeder_audit_spec.rb",
    "spec/lib/open_ehr/rm/common/archetyped/link_spec.rb",
    "spec/lib/open_ehr/rm/common/archetyped/locatable_spec.rb",
    "spec/lib/open_ehr/rm/common/archetyped/pathable_spec.rb",
    "spec/lib/open_ehr/rm/common/change_control/contribution_spec.rb",
    "spec/lib/open_ehr/rm/common/change_control/imported_version_spec.rb",
    "spec/lib/open_ehr/rm/common/change_control/original_version_spec.rb",
    "spec/lib/open_ehr/rm/common/change_control/version_spec.rb",
    "spec/lib/open_ehr/rm/common/change_control/versioned_object_spec.rb",
    "spec/lib/open_ehr/rm/common/directory/folder_spec.rb",
    "spec/lib/open_ehr/rm/common/generic/attestation_spec.rb",
    "spec/lib/open_ehr/rm/common/generic/audit_details_spec.rb",
    "spec/lib/open_ehr/rm/common/generic/participation_spec.rb",
    "spec/lib/open_ehr/rm/common/generic/party_identified_spec.rb",
    "spec/lib/open_ehr/rm/common/generic/party_proxy_spec.rb",
    "spec/lib/open_ehr/rm/common/generic/party_related_spec.rb",
    "spec/lib/open_ehr/rm/common/generic/revision_history_item_spec.rb",
    "spec/lib/open_ehr/rm/common/generic/revision_history_spec.rb",
    "spec/lib/open_ehr/rm/common/resource/authored_resource_spec.rb",
    "spec/lib/open_ehr/rm/common/resource/resource_description_item_spec.rb",
    "spec/lib/open_ehr/rm/common/resource/resource_description_spec.rb",
    "spec/lib/open_ehr/rm/common/resource/translation_details_spec.rb",
    "spec/lib/open_ehr/rm/composition/composition_spec.rb",
    "spec/lib/open_ehr/rm/composition/content/content_item_spec.rb",
    "spec/lib/open_ehr/rm/composition/content/entry/action_spec.rb",
    "spec/lib/open_ehr/rm/composition/content/entry/activity_spec.rb",
    "spec/lib/open_ehr/rm/composition/content/entry/admin_entry_spec.rb",
    "spec/lib/open_ehr/rm/composition/content/entry/care_entry_spec.rb",
    "spec/lib/open_ehr/rm/composition/content/entry/entry_spec.rb",
    "spec/lib/open_ehr/rm/composition/content/entry/evaluation_spec.rb",
    "spec/lib/open_ehr/rm/composition/content/entry/instruction_details_spec.rb",
    "spec/lib/open_ehr/rm/composition/content/entry/instruction_spec.rb",
    "spec/lib/open_ehr/rm/composition/content/entry/ism_transition_spec.rb",
    "spec/lib/open_ehr/rm/composition/content/entry/observation_spec.rb",
    "spec/lib/open_ehr/rm/composition/content/navigation/section_spec.rb",
    "spec/lib/open_ehr/rm/composition/event_context_spec.rb",
    "spec/lib/open_ehr/rm/data_structures/data_structure_spec.rb",
    "spec/lib/open_ehr/rm/data_structures/history/event_spec.rb",
    "spec/lib/open_ehr/rm/data_structures/history/history_spec.rb",
    "spec/lib/open_ehr/rm/data_structures/history/interval_event_spec.rb",
    "spec/lib/open_ehr/rm/data_structures/item_structure/item_list_spec.rb",
    "spec/lib/open_ehr/rm/data_structures/item_structure/item_single_spec.rb",
    "spec/lib/open_ehr/rm/data_structures/item_structure/item_table_spec.rb",
    "spec/lib/open_ehr/rm/data_structures/item_structure/item_tree_spec.rb",
    "spec/lib/open_ehr/rm/data_structures/item_structure/representation/cluster_spec.rb",
    "spec/lib/open_ehr/rm/data_structures/item_structure/representation/element_spec.rb",
    "spec/lib/open_ehr/rm/data_types/basic/data_value_spec.rb",
    "spec/lib/open_ehr/rm/data_types/basic/dv_boolean_spec.rb",
    "spec/lib/open_ehr/rm/data_types/basic/dv_identifier_spec.rb",
    "spec/lib/open_ehr/rm/data_types/basic/dv_state_spec.rb",
    "spec/lib/open_ehr/rm/data_types/encapsulated/dv_encapsulated_spec.rb",
    "spec/lib/open_ehr/rm/data_types/encapsulated/dv_multimedia_spec.rb",
    "spec/lib/open_ehr/rm/data_types/encapsulated/dv_parsable_spec.rb",
    "spec/lib/open_ehr/rm/data_types/quantity/date_time/dv_date_spec.rb",
    "spec/lib/open_ehr/rm/data_types/quantity/date_time/dv_date_time_spec.rb",
    "spec/lib/open_ehr/rm/data_types/quantity/date_time/dv_tempral_spec.rb",
    "spec/lib/open_ehr/rm/data_types/quantity/date_time/dv_time_spec.rb",
    "spec/lib/open_ehr/rm/data_types/quantity/dv_absolute_quantity_spec.rb",
    "spec/lib/open_ehr/rm/data_types/quantity/dv_amount_spec.rb",
    "spec/lib/open_ehr/rm/data_types/quantity/dv_count_spec.rb",
    "spec/lib/open_ehr/rm/data_types/quantity/dv_interval_spec.rb",
    "spec/lib/open_ehr/rm/data_types/quantity/dv_ordered_spec.rb",
    "spec/lib/open_ehr/rm/data_types/quantity/dv_ordinal_spec.rb",
    "spec/lib/open_ehr/rm/data_types/quantity/dv_proportion_spec.rb",
    "spec/lib/open_ehr/rm/data_types/quantity/dv_quantified_spec.rb",
    "spec/lib/open_ehr/rm/data_types/quantity/dv_quantity_spec.rb",
    "spec/lib/open_ehr/rm/data_types/quantity/proportion_kind_spec.rb",
    "spec/lib/open_ehr/rm/data_types/quantity/reference_range_spec.rb",
    "spec/lib/open_ehr/rm/data_types/text/code_phrase_spec.rb",
    "spec/lib/open_ehr/rm/data_types/text/dv_paragraph_spec.rb",
    "spec/lib/open_ehr/rm/data_types/text/dv_text_spec.rb",
    "spec/lib/open_ehr/rm/data_types/text/term_mapping_spec.rb",
    "spec/lib/open_ehr/rm/data_types/uri/dv_ehr_uri_spec.rb",
    "spec/lib/open_ehr/rm/data_types/uri/dv_uri_spec.rb",
    "spec/lib/open_ehr/rm/demographic/actor_spec.rb",
    "spec/lib/open_ehr/rm/demographic/address_spec.rb",
    "spec/lib/open_ehr/rm/demographic/capability_spec.rb",
    "spec/lib/open_ehr/rm/demographic/contact_spec.rb",
    "spec/lib/open_ehr/rm/demographic/party_identity_spec.rb",
    "spec/lib/open_ehr/rm/demographic/party_relationship_spec.rb",
    "spec/lib/open_ehr/rm/demographic/party_spec.rb",
    "spec/lib/open_ehr/rm/demographic/role_spec.rb",
    "spec/lib/open_ehr/rm/ehr/ehr_access_spec.rb",
    "spec/lib/open_ehr/rm/ehr/ehr_spec.rb",
    "spec/lib/open_ehr/rm/ehr/ehr_status_spec.rb",
    "spec/lib/open_ehr/rm/ehr/versioned_composition_spec.rb",
    "spec/lib/open_ehr/rm/integration/generic_entry_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/access_group_ref_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/archetype_id_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/generic_id_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/hier_object_id_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/internet_id_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/iso_oid_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/locatable_ref_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/object_id_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/object_ref_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/object_version_id_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/party_ref_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/template_id_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/terminology_id_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/uid_based_id_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/uid_spec.rb",
    "spec/lib/open_ehr/rm/support/identification/version_tree_id_spec.rb",
    "spec/lib/open_ehr/rm/support/measurement_service_spec.rb",
    "spec/lib/open_ehr/rm/support/terminology_service_spec.rb",
    "spec/lib/open_ehr/serializer/adl-test-entry.most_minimal.test.adl",
    "spec/lib/open_ehr/serializer/adl_serializer_spec.rb",
    "spec/lib/open_ehr/serializer/openEHR-EHR-SECTION.test.v1.adl",
    "spec/lib/open_ehr/serializer/openEHR-EHR-SECTION.test.v1.xml",
    "spec/lib/open_ehr/serializer/sample_archetype_spec.rb",
    "spec/lib/open_ehr/serializer/xml_serializer_spec.rb",
    "spec/lib/open_ehr/terminology/open_ehr_terminology_spec.rb",
    "spec/rcov.opts",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/skoba/ruby-impl-openehr}
  s.licenses = ["The openEHR Open Source Software license(mozilla tri-license)"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Ruby implementation of the openEHR specification}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xml-simple>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<locale>, [">= 0"])
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<spork>, [">= 0"])
    else
      s.add_dependency(%q<xml-simple>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<locale>, [">= 0"])
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<spork>, [">= 0"])
    end
  else
    s.add_dependency(%q<xml-simple>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<locale>, [">= 0"])
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<spork>, [">= 0"])
  end
end

