require_relative 'serializer/base'
require_relative 'serializer/adl_serializer'
require_relative 'serializer/xml_serializer'
require_relative 'serializer/opt_serializer'
require_relative 'serializer/rm_json_serializer'
